# Netlify build configuration file

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Configuration for Netlify Serverless Functions
[functions]
  # Wichtig: Hier muss die korrekte Google-Bibliothek stehen
  external_node_modules = ["@google/generative-ai"]
  node_bundler = "esbuild"

  # Ressourcen für die Hauptfunktion
  [functions.generate]
    memory = 1024

  # Ressourcen für die Vorschlags-Funktion
  [functions.generate-suggestion]
    memory = 1024
